"""The installer's code fingerprint: one sha256 over everything ISCC compiles into the exe, with the build-stamp lines
left out (so a rebuild of the same sources gives the same fingerprint, and any edit of the .iss code or a new catalog
gives a new one). Test results (tests\\run_all.py) record it; release.py --final and publish_github.py accept only
results made with the current fingerprint, and the release exe's sidecar (dist\\<tag>\\RELEASE_EXE.json) records the
fingerprint it was compiled from.

Standard library only (tests\\run_all.py imports this module too).

Inputs, in this order: CXCXM_v65_Installer.iss, code\\*.iss (sorted by name), generated\\build_info.iss,
generated\\catalog.iss, staging\\meta\\CXCXM_conv302_manifest.txt.
"""
from __future__ import annotations

import hashlib
import re
from pathlib import Path

INST = Path(__file__).resolve().parent.parent

# the lines that change on every emit although nothing else did
_STAMP_LINE = re.compile(r"(AUTO-GENERATED by the v6\.5 release pipeline|CAT_BUILD_STAMP\s*=|#define\s+BuildStamp\b)")


def code_files(inst: Path = INST) -> list[Path]:
    files = [inst / "CXCXM_v65_Installer.iss"]
    files += sorted((inst / "code").glob("*.iss"), key=lambda p: p.name.lower())
    files += [inst / "generated" / "build_info.iss", inst / "generated" / "catalog.iss",
              inst / "staging" / "meta" / "CXCXM_conv302_manifest.txt"]
    return files


def _normalized(p: Path) -> bytes:
    data = p.read_bytes()
    if p.suffix.lower() != ".iss":
        return data
    text = data.decode("utf-8", errors="replace").replace("\r\n", "\n")
    return "\n".join(l for l in text.split("\n") if not _STAMP_LINE.search(l)).encode("utf-8")


def code_fingerprint(inst: Path = INST) -> str:
    h = hashlib.sha256()
    for p in code_files(inst):
        rel = p.relative_to(inst).as_posix().lower()
        if not p.is_file():
            h.update(("MISSING " + rel + "\n").encode("utf-8"))
            continue
        d = _normalized(p)
        h.update(("%s %d\n" % (rel, len(d))).encode("utf-8"))
        h.update(d)
    return h.hexdigest()


if __name__ == "__main__":
    print(code_fingerprint())
