"""P8: generated\\catalog.iss (contract section 3, UTF-8 no BOM, LF) and generated\\build_info.iss (section 4).
A straight translation of the catalog model; InitCatalog is split into InitCatalog1..n when long."""
from __future__ import annotations

from . import cfg
from .util import log, pascal_str, require, write_text


def _lit(s: str) -> str:
    """one literal; non-ASCII characters become #<code> tokens so the include stays pure ASCII"""
    if s.isascii():
        return pascal_str(s)
    out, buf = [], ""
    for ch in s:
        if ord(ch) < 128:
            buf += ch
        else:
            if buf:
                out.append(pascal_str(buf))
                buf = ""
            require(ord(ch) <= 0xFFFF, "character outside the BMP in a catalog text: %r" % ch)
            out.append("#%d" % ord(ch))
    if buf:
        out.append(pascal_str(buf))
    return " + ".join(out)


def ps(s: str) -> str:
    """Pascal string literal; long ones are split into '...' + '...' pieces on separate lines"""
    if len(s) <= 180:
        return _lit(s)
    parts = [_lit(s[i:i + 160]) for i in range(0, len(s), 160)]
    # a line whose first non-blank character is '#' is an ISPP directive: never start a continuation line with #<code>
    parts = [("'' + " + p) if p.startswith("#") else p for p in parts]
    return (" +" + chr(10) + "      ").join(parts)

CHUNK = 400   # statements per InitCatalogN


def _b(x: bool) -> str:
    return "True" if x else "False"


def catalog_iss(m: dict, cat_sha: str, stamp: str) -> str:
    comps = m["components"]
    states = [s for c in comps for s in c["states"]]
    arch = m["archives"]
    pins = [p for a in arch for p in a["pins"]]
    mems = [x for a in arch for x in a["members"]]
    nat_lines = [l for n in m["natives"] for l in n["lines"]]
    counts = {
        "COMP": len(comps), "STATE": len(states), "RULE": len(m["rules"]), "PATH": len(m["paths"]), "AFF": len(m["aff"]),
        "TAB": len(m["tab"]), "VAR": len(m["variants"]), "ARCH": len(arch), "PIN": len(pins), "MEM": len(mems),
        "BLOB": len(m["blobs"]), "URL": len(m["base_urls"]), "NAT": len(m["natives"]), "NATLINE": len(nat_lines),
        "DET": len(m["detection"]), "OBS": len(m["obsolete"]), "FIELD": len(m["fields"]), "CREDIT": len(m["credits"]),
    }
    seam = [a for a in arch if a["mode"] == "V" and a.get("tested")]
    L = []
    L.append("{ ======================================================================")
    L.append("  AUTO-GENERATED by the v6.5 release pipeline (pipeline\\emit_iss.py) on %s." % stamp)
    L.append("  DO NOT EDIT BY HAND. Contract: installer\\README_CONTRACT.md (CAT_FORMAT %d)." % m["format"])
    L.append("  RC %s, catalog.json sha256 %s" % (m["rc"], cat_sha))
    L.append("  ====================================================================== }")
    L.append("")
    L.append("const")
    L.append("  CAT_FORMAT        = %d;" % m["format"])
    L.append("  CAT_VERSION       = %s;" % ps(m["version"]))
    L.append("  CAT_VERSION_SHORT = %s;" % ps(m["version_short"]))
    L.append("  CAT_MOD_TITLE     = %s;" % ps(m["mod_title"]))
    L.append("  CAT_RC            = %s;" % ps(m["rc"]))
    L.append("  CAT_RELEASE_TAG   = %s;" % ps(m["tag"]))
    L.append("  CAT_BUILD_STAMP   = %s;" % ps(stamp))
    L.append("  CAT_SHA256        = %s;" % ps(cat_sha))
    L.append("  CAT_CHANGELOG_REL = %s;" % ps(m["changelog_rel"]))
    L.append("  CAT_NEXUS_URL     = %s;" % ps(m["nexus_url"]))
    for k, v in counts.items():
        L.append("  CAT_%s_COUNT = %d;" % (k, v))
    for i, c in enumerate(comps):
        L.append("  CAT_C_%s = %d;" % (c["id"].upper(), i))
    L.append("  WALL_BASE         = %d;   { clip-list total of MAIN alone (%s) }" % (m["wall"]["base"], m["rc"]))
    L.append("  WALL_LIMIT_NODLL  = %d;" % m["wall"]["limit_nodll"])
    L.append("  WALL_LIMIT_DLL    = %d;" % m["wall"]["limit_dll"])
    dll = m["wall"]["dll_comp"]
    L.append("  WALL_DLL_COMP     = %d;   { %s }" % (dll, ("CAT_C_" + comps[dll]["id"].upper()) if dll >= 0 else "none"))
    L.append("  MAX_REL_LEN       = %d;" % m["max_rel_len"])
    L.append("  MAX_REL_DIR_LEN   = %d;" % m["max_rel_dir_len"])
    L.append("  CONV_MANIFEST_FILE  = %s;" % ps(m["conv_manifest"]["file"]))
    L.append("  CONV_MANIFEST_MAGIC = %s;" % ps(m["conv_manifest"]["magic"]))
    L.append("  CONV302_FILE_COUNT  = %d;" % m["conv302_file_count"])
    L.append("  { extra (additive, not in the contract's list): the tested Seamless Co-op version, for the marker }")
    if seam:
        a = seam[0]
        ersc = [s for t, s in a["tested"]["members"].items() if t.lower().endswith("ersc.dll")]
        L.append("  CAT_SEAMLESS_TESTED_VERSION = %s;" % ps(a["tested"]["version"]))
        L.append("  CAT_SEAMLESS_TESTED_ERSC_SHA256 = %s;" % ps(ersc[0] if ersc else ""))
    else:
        L.append("  CAT_SEAMLESS_TESTED_VERSION = '';")
        L.append("  CAT_SEAMLESS_TESTED_ERSC_SHA256 = '';")
    L.append("")

    S = []   # statements of InitCatalog

    def setlen(name, n):
        S.append("SetArrayLength(%s, %d);" % (name, n))

    for name in ("CompId", "CompSwitch", "CompTitle", "CompDesc", "CompKind", "CompExperimental", "CompDefault",
                 "CompStateCount", "CompStateStart", "CompCredit", "CompSourceText"):
        setlen(name, counts["COMP"])
    for i, c in enumerate(comps):
        S.append("CompId[%d] := %s; CompSwitch[%d] := %s; CompKind[%d] := %s; CompExperimental[%d] := %s; "
                 "CompDefault[%d] := %d; CompStateCount[%d] := %d; CompStateStart[%d] := %d;" % (
                     i, ps(c["id"]), i, ps(c["switch"]), i, ps(c["kind"]), i, _b(c["experimental"]), i, c["default"],
                     i, len(c["states"]), i, c["state_start"]))
        S.append("CompTitle[%d] := %s;" % (i, ps(c["title"])))
        S.append("CompDesc[%d] := %s;" % (i, ps(c["desc"])))
        S.append("CompCredit[%d] := %s; CompSourceText[%d] := %s;" % (i, ps(c["credit"]), i, ps(c["source_text"])))
    for name in ("StateCode", "StateTitle", "StateWall"):
        setlen(name, counts["STATE"])
    for i, s in enumerate(states):
        S.append("StateCode[%d] := %s; StateTitle[%d] := %s; StateWall[%d] := %d;" % (
            i, ps(s["code"]), i, ps(s["title"]), i, s["wall"]))
    # the exact wall total of every combination of the animation-touching components (additive extension, rc8 switch
    # prep 2026-10-03; empty = the additive model; the first component's state counts fastest)
    wc, wt = m["wall"].get("combo_comps", []), m["wall"].get("combo_totals", [])
    setlen("WallComboComp", len(wc))
    for i, c in enumerate(wc):
        S.append("WallComboComp[%d] := %d;" % (i, c))
    setlen("WallComboTotal", len(wt))
    for i, t in enumerate(wt):
        S.append("WallComboTotal[%d] := %d;" % (i, t))
    for name in ("RuleKind", "RuleA", "RuleAMask", "RuleB", "RuleBMask", "RuleText"):
        setlen(name, counts["RULE"])
    for i, r in enumerate(m["rules"]):
        S.append("RuleKind[%d] := %s; RuleA[%d] := %d; RuleAMask[%d] := %d; RuleB[%d] := %d; RuleBMask[%d] := %d;" % (
            i, ps(r["kind"]), i, r["a"], i, r["a_mask"], i, r["b"], i, r["b_mask"]))
        S.append("RuleText[%d] := %s;" % (i, ps(r["text"])))
    for name in ("PathRel", "PathFlags", "PathOwner", "PathAffStart", "PathAffCount", "PathTabStart"):
        setlen(name, counts["PATH"])
    for i, p in enumerate(m["paths"]):
        S.append("PathRel[%d] := %s; PathFlags[%d] := %s; PathOwner[%d] := %d; PathAffStart[%d] := %d; "
                 "PathAffCount[%d] := %d; PathTabStart[%d] := %d;" % (
                     i, ps(p["rel"]), i, ps(p["flags"]), i, p["owner"], i, p["aff_start"], i, len(p["affects"]),
                     i, p["tab_start"]))
    setlen("AffComp", counts["AFF"])
    for i in range(0, len(m["aff"]), 12):
        S.append(" ".join("AffComp[%d] := %d;" % (j, m["aff"][j]) for j in range(i, min(i + 12, len(m["aff"])))))
    setlen("PathTab", counts["TAB"])
    for i in range(0, len(m["tab"]), 12):
        S.append(" ".join("PathTab[%d] := %d;" % (j, m["tab"][j]) for j in range(i, min(i + 12, len(m["tab"])))))
    for name in ("VarPath", "VarSha", "VarSize", "VarSrc", "VarRef"):
        setlen(name, counts["VAR"])
    for i, v in enumerate(m["variants"]):
        S.append("VarPath[%d] := %d; VarSha[%d] := %s; VarSize[%d] := %d; VarSrc[%d] := %s; VarRef[%d] := %d;" % (
            i, v["path"], i, ps(v["sha256"]), i, v["size"], i, ps(v["src"]), i, v["ref"]))
    for name in ("ArchId", "ArchComp", "ArchTitle", "ArchAuthor", "ArchHint", "ArchNexusUrl", "ArchNameHints", "ArchMode",
                 "ArchMustVerify", "ArchGlobs", "ArchPinStart", "ArchPinCount", "ArchMemStart", "ArchMemCount"):
        setlen(name, counts["ARCH"])
    for i, a in enumerate(arch):
        S.append("ArchId[%d] := %s; ArchComp[%d] := %d; ArchMode[%d] := %s; ArchMustVerify[%d] := %s; "
                 "ArchPinStart[%d] := %d; ArchPinCount[%d] := %d; ArchMemStart[%d] := %d; ArchMemCount[%d] := %d;" % (
                     i, ps(a["id"]), i, a["comp"], i, ps(a["mode"]), i, _b(a["must_verify"]), i, a["pin_start"],
                     i, len(a["pins"]), i, a["mem_start"], i, len(a["members"])))
        S.append("ArchTitle[%d] := %s;" % (i, ps(a["title"])))
        S.append("ArchAuthor[%d] := %s;" % (i, ps(a["author"])))
        S.append("ArchHint[%d] := %s;" % (i, ps(a["hint"])))
        S.append("ArchNexusUrl[%d] := %s;" % (i, ps(a["nexus_url"])))
        S.append("ArchNameHints[%d] := %s;" % (i, ps("|".join(a["name_hints"]))))
        S.append("ArchGlobs[%d] := %s;" % (i, ps("|".join(a["globs"]))))
    for name in ("PinSize", "PinSha"):
        setlen(name, counts["PIN"])
    for i, p in enumerate(pins):
        S.append("PinSize[%d] := %d; PinSha[%d] := %s;" % (i, p["size"], i, ps(p["sha256"])))
    for name in ("MemArch", "MemName", "MemTail", "MemSha", "MemSize"):
        setlen(name, counts["MEM"])
    mi = 0
    for ai, a in enumerate(arch):
        for x in a["members"]:
            # mode V: MemSha = the TESTED version's sha256 (contract change log, repair 1): the runtime never requires
            # it (any version is accepted when the player picks it), it only decides "tested version" or not
            sha = x["sha256"] if a["mode"] == "P" else x.get("tested_sha256", "")
            S.append("MemArch[%d] := %d; MemName[%d] := %s; MemSha[%d] := %s; MemSize[%d] := %d;" % (
                mi, ai, mi, ps(x["name"]), mi, ps(sha), mi, x["size"]))
            S.append("MemTail[%d] := %s;" % (mi, ps(x["tail"])))
            mi += 1
    for name in ("BlobSha", "BlobSize", "BlobAsset", "BlobTag", "BlobUpstream", "BlobSite"):
        setlen(name, counts["BLOB"])
    for i, b in enumerate(m["blobs"]):
        S.append("BlobSha[%d] := %s; BlobSize[%d] := %d; BlobTag[%d] := %s;" % (
            i, ps(b["sha256"]), i, b["size"], i, ps(b["tag"])))
        S.append("BlobAsset[%d] := %s; BlobUpstream[%d] := %s; BlobSite[%d] := %s;" % (
            i, ps(b["asset"]), i, ps(b["upstream"]), i, ps(b.get("site", ""))))
    setlen("BaseUrls", counts["URL"])
    for i, u in enumerate(m["base_urls"]):
        S.append("BaseUrls[%d] := %s;" % (i, ps(u)))
    for name in ("NatComp", "NatMatch", "NatPath", "NatForeign", "NatLf", "NatLineStart", "NatLineCount"):
        setlen(name, counts["NAT"])
    setlen("NatLine", counts["NATLINE"])
    li = 0
    for i, n in enumerate(m["natives"]):
        S.append("NatComp[%d] := %d; NatMatch[%d] := %s; NatForeign[%d] := %s; NatLf[%d] := %s; NatLineStart[%d] := %d; "
                 "NatLineCount[%d] := %d;" % (i, n["comp"], i, ps(n["match"]), i, ps(n["foreign"]), i, _b(n["lf"]),
                                             i, li, i, len(n["lines"])))
        S.append("NatPath[%d] := %s;" % (i, ps(n["path_sq"])))
        for ln in n["lines"]:
            S.append("NatLine[%d] := %s;" % (li, ps(ln)))
            li += 1
    for pi, lines in enumerate(m["pristine_me3"]):
        setlen("PristineMe3Lines%d" % pi, len(lines))
        for j, ln in enumerate(lines):
            S.append("PristineMe3Lines%d[%d] := %s;" % (pi, j, ps(ln)))
    for name in ("DetComp", "DetKind", "DetArg", "DetSha", "DetState"):
        setlen(name, counts["DET"])
    for i, d in enumerate(m["detection"]):
        S.append("DetComp[%d] := %d; DetKind[%d] := %s; DetState[%d] := %d; DetSha[%d] := %s;" % (
            i, d["comp"], i, ps(d["kind"]), i, d["state"], i, ps(d["sha"])))
        S.append("DetArg[%d] := %s;" % (i, ps(d["arg"])))
    for name in ("ObsRel", "ObsSha", "ObsNote"):
        setlen(name, counts["OBS"])
    for i, o in enumerate(m["obsolete"]):
        S.append("ObsRel[%d] := %s; ObsSha[%d] := %s;" % (i, ps(o["rel"]), i, ps(o["sha256"])))
        S.append("ObsNote[%d] := %s;" % (i, ps(o["note"])))
    for name in ("FieldComp", "FieldId", "FieldSwitch", "FieldLabel", "FieldRel", "FieldSection", "FieldKey", "FieldSecret"):
        setlen(name, counts["FIELD"])
    for i, f in enumerate(m["fields"]):
        S.append("FieldComp[%d] := %d; FieldId[%d] := %s; FieldSwitch[%d] := %s; FieldSecret[%d] := %s;" % (
            i, f["comp"], i, ps(f["id"]), i, ps(f["switch"]), i, _b(f["secret"])))
        S.append("FieldLabel[%d] := %s;" % (i, ps(f["label"])))
        S.append("FieldRel[%d] := %s; FieldSection[%d] := %s; FieldKey[%d] := %s;" % (
            i, ps(f["rel"]), i, ps(f["section"]), i, ps(f["key"])))
    for name in ("CreditComp", "CreditText"):
        setlen(name, counts["CREDIT"])
    for i, c in enumerate(m["credits"]):
        S.append("CreditComp[%d] := %d; CreditText[%d] := %s;" % (i, c["comp"], i, ps(c["text"])))

    chunks = [S[i:i + CHUNK] for i in range(0, len(S), CHUNK)]
    for n, ch in enumerate(chunks, 1):
        L.append("procedure InitCatalog%d;" % n)
        L.append("begin")
        L += ["  " + s for s in ch]
        L.append("end;")
        L.append("")
    L.append("procedure InitCatalog;")
    L.append("begin")
    for n in range(1, len(chunks) + 1):
        L.append("  InitCatalog%d;" % n)
    L.append("end;")
    L.append("")
    text = "\n".join(L)
    require("\r" not in text, "CR in generated text")
    return text


def build_info_iss(m: dict, cat_sha: str, stamp: str) -> str:
    v = m["version"]
    return "\n".join([
        "; AUTO-GENERATED by the v6.5 release pipeline (pipeline\\emit_iss.py) on %s. DO NOT EDIT BY HAND." % stamp,
        "#define CatFormat %d" % m["format"],
        '#define CatVersion "%s"' % v,
        '#define CatRc "%s"' % m["rc"],
        '#define CatSha256 "%s"' % cat_sha,
        '#define BuildStamp "%s"' % stamp,
        '#define InstallerBaseName "%s"' % m["installer_base_name"],
        '#define VersionInfo "%s.0"' % v,
        "",
    ])


def emit(m: dict, cat_sha: str, stamp: str) -> dict:
    t = catalog_iss(m, cat_sha, stamp)
    write_text(cfg.CATALOG_ISS, t)
    b = build_info_iss(m, cat_sha, stamp)
    write_text(cfg.BUILD_INFO_ISS, b)
    n_lines = t.count("\n")
    log("generated %s (%d lines, %d KB) and %s" % (cfg.CATALOG_ISS, n_lines, len(t) // 1024, cfg.BUILD_INFO_ISS.name))
    return {"catalog_iss_lines": n_lines}
